import type { QuestionConfig } from "@/types/onboarding.types";

export const ONBOARDING_QUESTIONS: QuestionConfig[] = [
  {
    step: 1,
    endpoint: "q1",
    fieldName: "occupation",
    bodyKey: "occupation",
    type: "single",
    title: "What is your current occupation?",
    subtitle: "We'll use this information to personalize your plan.",
    options: [
      { value: "student", label: "Student" },
      { value: "developer", label: "Developer" },
      { value: "designer", label: "Designer" },
      { value: "teacher", label: "Teacher" },
      { value: "freelancer", label: "Freelancer" },
      { value: "doctor", label: "Doctor" },
      { value: "parent", label: "Parent" },
      { value: "other", label: "Other" },
    ],
  },
  {
    step: 2,
    endpoint: "q2",
    fieldName: "language",
    bodyKey: "language",
    type: "single",
    title: "Which language do you prefer?",
    subtitle: "We'll use this information to personalize your plan.",
    options: [
      { value: "arabic", label: "Arabic" },
      { value: "english", label: "English" },
      { value: "mixed", label: "Mixed", sublabel: "عربي + English" },
    ],
  },
  {
    step: 3,
    endpoint: "q3",
    fieldName: "learningStyle",
    bodyKey: "learningStyle",
    type: "single",
    title: "What is your preferred learning style?",
    subtitle: "Choose how you process information best.",
    options: [
      { value: "visual", label: "Visual" },
      { value: "auditory", label: "Auditory" },
      { value: "kinesthetic", label: "Kinesthetic" },
      { value: "reading", label: "Reading" },
    ],
  },
  {
    step: 4,
    endpoint: "q4",
    fieldName: "motivations",
    bodyKey: "motivations",
    type: "multi",
    title: "What motivates you the most?",
    subtitle: "Choose your preferred rewards to stay on track.",
    options: [
      { value: "points", label: "Points" },
      { value: "streaks", label: "Streaks" },
      { value: "praise", label: "Praise" },
      { value: "badges", label: "Badges" },
      { value: "visual_progress", label: "Visual Progress" },
    ],
  },
  {
    step: 5,
    endpoint: "q5",
    fieldName: "challenges",
    bodyKey: "challenges",
    type: "multi",
    title: "What are your main daily challenges?",
    subtitle: "Select the common challenges you face.",
    options: [
      { value: "procrastination", label: "Procrastination" },
      { value: "overwhelm", label: "Overwhelm" },
      { value: "distraction", label: "Distraction" },
      { value: "time_blindness", label: "Time Blindness" },
      { value: "impulsivity", label: "Impulsivity" },
      { value: "forgetfulness", label: "Forgetfulness" },
    ],
  },
  {
    step: 6,
    endpoint: "q6",
    fieldName: "focusTimeOfDay",
    bodyKey: "focusTimeOfDay",
    type: "single",
    title: "When do you feel most focused?",
    subtitle: "Select the time of day your energy pattern is highest.",
    options: [
      { value: "morning", label: "Morning" },
      { value: "afternoon", label: "Afternoon" },
      { value: "evening", label: "Evening" },
    ],
  },
  {
    step: 7,
    endpoint: "q7",
    fieldName: "primaryGoal",
    bodyKey: "primaryGoal",
    type: "single",
    title: "What is your primary goal?",
    subtitle: "Select your focus goals for LUMO.",
    options: [
      { value: "personal", label: "Personal Goal" },
      { value: "occupation_specific", label: "Occupation-Specific Goal" },
      { value: "general", label: "General Goal" },
    ],
  },
  {
    step: 8,
    endpoint: "q8",
    fieldName: "adhdSeverity",
    bodyKey: "adhdSeverity",
    type: "single",
    title: "Your ADHD Profile Analysis",
    subtitle:
      "Based on your answers, we've analyzed your symptom severity level.",
    options: [
      { value: "mild", label: "Mild Symptoms" },
      { value: "moderate", label: "Moderate Symptoms" },
      { value: "severe", label: "Severe Symptoms" },
    ],
  },
  {
    step: 9,
    endpoint: "q9",
    fieldName: "focusDuration",
    bodyKey: "focusDuration",
    type: "single",
    title: "Your Personalized Focus Goal",
    subtitle:
      "We've set your maximum continuous focus duration based on your profile severity to avoid burnout.",
    options: [
      { value: "5-10", label: "5–10 Minutes Focus Session" },
      { value: "10-15", label: "10–15 Minutes Focus Session" },
      { value: "15-20", label: "15–20 Minutes Focus Session" },
      { value: "20-25", label: "20–25 Minutes Focus Session" },
      { value: "25-30", label: "25–30 Minutes Focus Session" },
    ],
  },
  {
    step: 10,
    endpoint: "q10",
    fieldName: "adhdType",
    bodyKey: "adhdType",
    type: "single",
    title: "Which ADHD type describes your experience best?",
    subtitle:
      "Select the option that aligns closest with your primary symptoms.",
    options: [
      {
        value: "inattentive",
        label: "Inattentive",
        sublabel: "صعوبة في التركيز والتنظيم",
      },
      {
        value: "hyperactive",
        label: "Hyperactive",
        sublabel: "اندفاع وحركة زائدة",
      },
      {
        value: "combined",
        label: "Combined",
        sublabel: "المشكلتين موجودتين معاً",
      },
    ],
  },
];

export const TOTAL_STEPS = ONBOARDING_QUESTIONS.length;
